# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_version = ">= 1.6.3"
  required_plugins {
    vsphere = {
      version = "~> 2"
      source  = "github.com/vmware/vsphere"
    }
  }
}

variable "builder_datacenter" {
  type    = string
  default = ""
}
variable "builder_host" {
  type = string
}

variable "builder_host_datastore" {
  type = string
}

variable "builder_host_password" {
  type = string
}

variable "builder_host_portgroup" {
  type = string
}

variable "builder_host_username" {
  type = string
}

variable "builder_vcenter_server" {
  type    = string
  default = ""
}

variable "content_library_disk_size" {
  type    = number
  default = 614400
}

variable "cores_per_socket" {
  type    = number
  default = 1
}

variable "depot_disk_size" {
  type    = number
  default = 204800
}

variable "description" {
  type    = string
  default = "VCF Infrastructure Services Appliance"
}

variable "disk_size" {
  type    = number
  default = 40960
}

variable "dns_disk_size" {
  type    = number
  default = 2048
}

variable "guest_password" {
  type = string
}

variable "guest_username" {
  type = string
}

variable "harbor_admin_password" {
  type    = string
  default = ""
}

variable "harbor_http_port" {
  type    = string
  default = "9080"
}

variable "harbor_port" {
  type    = string
  default = "9443"
}

variable "harbor_version" {
  type    = string
  default = "v2.15.1"
}

variable "identity_disk_size" {
  type    = number
  default = 2048
}

variable "install_vcf_download_tool" {
  type    = string
  default = "false"
}

variable "iso_checksum" {
  type = string
}

variable "iso_url" {
  type = string
}

variable "keycloak_image" {
  type    = string
  default = "quay.io/keycloak/keycloak:26.3"
}

variable "numvcpus" {
  type = string
}

variable "ovftool_deploy_vcenter" {
  type    = string
  default = "192.168.30.3"
}

variable "ovftool_deploy_vcenter_password" {
  type    = string
  default = "VMware1!"
}

variable "ovftool_deploy_vcenter_username" {
  type    = string
  default = "administrator@vsphere.local"
}

variable "ramsize" {
  type = string
}

variable "registry_disk_size" {
  type    = number
  default = 61440
}

variable "sftp_disk_size" {
  type    = number
  default = 15360
}

variable "storage_controller" {
  type    = string
  default = "scsi" # must be one of lsilogic, lsilogic-sas, pvscsi, nvme, scsi, or sata
}

variable "use_thin_provisioning" {
  type    = bool
  default = true
}

variable "version" {
  type = string
}

variable "vis_admin_password" {
  type    = string
  default = "VMware1!"
}

variable "vis_admin_username" {
  type    = string
  default = "admin"
}

variable "vis_appliance_fqdn" {
  type    = string
  default = "vis.vcf.lab"
}

variable "vis_appliance_ip" {
  type    = string
  default = "172.30.0.9"
}

variable "vis_ovf_template" {
  type    = string
  default = "vis.xml.template"
}

variable "vis_pod_cidr_network" {
  type    = string
  default = "10.10.0.0/16"
}

variable "vis_sftp_password" {
  type    = string
  default = ""
}

variable "vis_sftp_user" {
  type    = string
  default = ""
}

variable "vm_name" {
  type = string
}

locals {
  disks = [
    var.disk_size,
    var.depot_disk_size,
    var.sftp_disk_size,
    var.registry_disk_size,
    var.dns_disk_size,
    var.identity_disk_size,
    var.content_library_disk_size,
  ]
}

source "vsphere-iso" "ovf-builder" {
  # Properties here are listed as they appear in https://developer.hashicorp.com/packer/integrations/vmware/vsphere/latest/components/builder/vsphere-iso#http-configuration
  # HTTP Configuration
  http_directory = "http"

  # Connection Configuration
  vcenter_server      = var.builder_vcenter_server
  username            = var.builder_host_username
  password            = var.builder_host_password
  insecure_connection = true
  datacenter          = var.builder_datacenter

  # Location Configuration
  vm_name   = var.vm_name
  host      = var.builder_host
  datastore = var.builder_host_datastore
  export {
    output_format    = "ovf"
    output_directory = "output-vmware-iso" # for backward compatibility
  }

  # Hardware Configuration
  CPUs      = var.numvcpus
  cpu_cores = var.cores_per_socket
  RAM       = var.ramsize

  # Create Configuration
  vm_version    = 13
  guest_os_type = "ubuntu64Guest"
  notes         = "${var.description}|0AVersion: ${var.version}"
  network_adapters {
    network      = var.builder_host_portgroup
    network_card = "vmxnet3"
  }

  # ISO Configuration
  iso_checksum = var.iso_checksum
  iso_url      = var.iso_url

  # Storage Configuration
  disk_controller_type = [var.storage_controller]
  dynamic "storage" {
    for_each = local.disks
    iterator = disk_size
    content {
      disk_size             = disk_size.value
      disk_thin_provisioned = var.use_thin_provisioning
    }
  }

  # Boot Configuration
  boot_command           = ["<esc><wait>", "c<wait>", "linux /casper/vmlinuz autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>"]
  boot_keygroup_interval = "500ms"
  boot_wait              = "5s"

  # SSH Configuration
  ssh_password = var.guest_password
  ssh_port     = 22
  ssh_timeout  = "90m"
  ssh_username = var.guest_username

  # Shutdown Configuration
  shutdown_command = "echo '${var.guest_password}' | sudo -S shutdown -P now"
  shutdown_timeout = "15m"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.vsphere-iso.ovf-builder"]

  provisioner "shell-local" {
    inline = ["rm -rf http/optional-artifacts", "mkdir -p http/optional-artifacts", "touch http/optional-artifacts/.keep", "sh -c 'if [ \"${var.install_vcf_download_tool}\" = \"true\" ]; then set -- artifacts/vcf-download-tool-*; if [ -e \"$1\" ]; then cp \"$1\" http/optional-artifacts/vcf-download-tool-local.tar.gz; else : > http/optional-artifacts/vcf-download-tool-local.tar.gz; fi; else : > http/optional-artifacts/vcf-download-tool-local.tar.gz; fi'"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["scripts/vis-settings.sh"]
  }

  provisioner "file" {
    destination = "/tmp"
    source      = "vis"
  }

  provisioner "file" {
    destination = "/tmp/vis-redirect.service"
    source      = "files/vis-redirect.service"
  }

  provisioner "file" {
    destination = "/tmp/vis-update.sh"
    source      = "scripts/vis-update.sh"
  }

  provisioner "file" {
    destination = "/tmp/vis-apply-update.sh"
    source      = "scripts/vis-apply-update.sh"
  }

  provisioner "file" {
    destination = "/tmp/vis-offline-update.sh"
    source      = "scripts/vis-offline-update.sh"
  }
  
  provisioner "file" {
    destination = "/tmp/vis-update-signing.pub"
    source      = "files/vis-update-signing.pub"
  }
  
  provisioner "shell" {
    inline = ["mkdir -p /tmp/vis-optional-files", "if [ -n \"$${PACKER_HTTP_ADDR:-}\" ]; then curl -fsS -o /tmp/vis-optional-files/vcf-download-tool-local.tar.gz \"http://$${PACKER_HTTP_ADDR}/optional-artifacts/vcf-download-tool-local.tar.gz\" || :; fi"]
  }

  provisioner "shell" {
    environment_vars = ["VIS_INSTALL_VCF_DOWNLOAD_TOOL=${var.install_vcf_download_tool}"]
    execute_command  = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts          = ["scripts/vis-download-tool.sh"]
  }

  provisioner "shell" {
    environment_vars = ["VIS_APPLIANCE_FQDN=${var.vis_appliance_fqdn}", "VIS_APPLIANCE_IP=${var.vis_appliance_ip}", "VIS_ADMIN_USERNAME=${var.vis_admin_username}", "VIS_ADMIN_PASSWORD=${var.vis_admin_password}", "VIS_SFTP_USER=${var.vis_sftp_user}", "VIS_SFTP_PASSWORD=${var.vis_sftp_password}"]
    execute_command  = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts          = ["scripts/vis-services.sh"]
  }

  provisioner "shell" {
    environment_vars = ["VIS_APPLIANCE_FQDN=${var.vis_appliance_fqdn}", "VIS_APPLIANCE_IP=${var.vis_appliance_ip}", "VIS_POD_CIDR_NETWORK=${var.vis_pod_cidr_network}", "HARBOR_VERSION=${var.harbor_version}", "VIS_KEYCLOAK_IMAGE=${var.keycloak_image}", "VIS_HARBOR_PORT=${var.harbor_port}", "VIS_HARBOR_HTTP_PORT=${var.harbor_http_port}", "VIS_HARBOR_ADMIN_PASSWORD=${var.harbor_admin_password}"]
    execute_command  = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts          = ["scripts/vis-harbor.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    pause_before    = "10s"
    scripts         = ["scripts/vis-cleanup.sh"]
  }

  provisioner "file" {
    destination = "/tmp/rc.local"
    source      = "files/rc.local"
  }

  provisioner "file" {
    destination = "/tmp/getOvfProperty.py"
    source      = "files/getOvfProperty.py"
  }

  provisioner "file" {
    destination = "/tmp/setup.sh"
    source      = "files/setup.sh"
  }

  provisioner "file" {
    destination = "/tmp/setup-01-os.sh"
    source      = "files/setup-01-os.sh"
  }

  provisioner "file" {
    destination = "/tmp/setup-02-network.sh"
    source      = "files/setup-02-network.sh"
  }

  provisioner "file" {
    destination = "/tmp/setup-03-vis.sh"
    source      = "files/setup-03-vis.sh"
  }

  provisioner "shell" {
    execute_command = "echo '${var.guest_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["scripts/vis-firstboot.sh"]
  }

  post-processor "shell-local" {
    environment_vars = ["VIS_VERSION=${var.version}", "VIS_APPLIANCE_NAME=${var.vm_name}", "FINAL_VIS_APPLIANCE_NAME=${var.vm_name}", "VIS_OVF_TEMPLATE=${var.vis_ovf_template}"]
    inline           = ["cd manual", "./add_ovf_properties.sh"]
  }
}
