import os

from .models import ServiceDefinition, ValidationResult

APPLIANCE_FQDN = os.environ.get("VIS_APPLIANCE_FQDN", "vis.williamlam.local")
APPLIANCE_DOMAIN = ".".join(APPLIANCE_FQDN.split(".")[1:]) or "local"
DEFAULT_IDENTITY_GROUPS = [
    {"id": "vcf-admins", "name": "vcf-admins", "description": "Administrators of the VCF Platform", "members": []},
    {"id": "vcf-users", "name": "vcf-users", "description": "Users of the VCF Platform", "members": []},
]


INITIAL_SERVICES = [
    ServiceDefinition(
        id="web-depot",
        name="Software Depot",
        description="Software depot web server for VCF bundles, manifests, and async patch content.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"http://{APPLIANCE_FQDN}:8081/",
        filesystem_root="/opt/vis/data/depot",
        settings={
            "protocol": "http",
            "port": 8081,
            "path": "/",
            "basic_auth_enabled": False,
            "auth_user": "",
            "auth_password": "",
            "download_mode": "manual",
            "download_token": "",
            "activation_code": "",
            "download_credential_path": "",
            "vcfdt_system_id": "",
            "last_metadata_download": "",
            "tls_enabled": False,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
        },
        last_validation_result=ValidationResult(False, "Software Depot is not configured yet", ""),
        quick_actions=["Files", "Configure", "Restart"],
    ),
    ServiceDefinition(
        id="sftp-backup",
        name="SFTP Backup",
        description="SFTP endpoint for VCF component backup targets with appliance-local storage.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"sftp://{APPLIANCE_FQDN}/backup",
        filesystem_root="/opt/vis/data/sftp/backup",
        settings={
            "protocol": "sftp",
            "port": 22,
            "path": "/backup",
            "user": "",
            "chroot": True,
            "password": "",
        },
        last_validation_result=ValidationResult(False, "SFTP credentials are not configured", ""),
        quick_actions=["Reset Password", "Configure", "Restart"],
    ),
    ServiceDefinition(
        id="harbor-registry",
        name="Container Registry",
        description="Container registry service for disconnected VCF and Kubernetes-adjacent workflows.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"http://{APPLIANCE_FQDN}:9080/",
        filesystem_root="/opt/vis/data/registry",
        settings={
            "protocol": "http",
            "port": 9080,
            "path": "/",
            "mode": "port",
            "tls_enabled": False,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
            "admin_user": "",
            "admin_password": "",
        },
        last_validation_result=ValidationResult(False, "Certificate configuration required", ""),
        quick_actions=["Enable", "Configure"],
    ),
    ServiceDefinition(
        id="ldap-provider",
        name="LDAP Provider",
        description="OpenLDAP-compatible directory service for traditional identity integrations.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"ldap://{APPLIANCE_FQDN}:389",
        filesystem_root="/opt/vis/data/identity/directory",
        settings={
            "protocol": "ldap",
            "port": 389,
            "path": "",
            "mode": "port",
            "provider": "openldap",
            "base_dn": "",
            "bind_dn": "",
            "admin_user": "",
            "admin_password": "",
            "users": [],
            "groups": [dict(group) for group in DEFAULT_IDENTITY_GROUPS],
            "tls_enabled": False,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
        },
        last_validation_result=ValidationResult(False, "LDAP provider is not configured yet", ""),
        quick_actions=["Configure"],
    ),
    ServiceDefinition(
        id="oidc-provider",
        name="OIDC Provider",
        description="Keycloak-based OIDC provider for modern authentication integrations.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"http://{APPLIANCE_FQDN}:9081/",
        filesystem_root="/opt/vis/data/identity/oidc",
        settings={
            "protocol": "http",
            "port": 9081,
            "path": "/",
            "mode": "port",
            "provider": "keycloak",
            "image": "quay.io/keycloak/keycloak:26.3",
            "login_theme": "vis",
            "realm": "VCF",
            "default_group": "vcf-admins",
            "admin_user": "admin",
            "admin_password": "",
            "users": [],
            "groups": [dict(group) for group in DEFAULT_IDENTITY_GROUPS],
            "oidc_clients": [],
            "tls_enabled": False,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
        },
        last_validation_result=ValidationResult(False, "OIDC provider is not configured yet", ""),
        quick_actions=["Configure"],
    ),
    ServiceDefinition(
        id="unbound-dns",
        name="DNS Server",
        description="Local DNS resolver and authoritative records for appliance lab zones.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"dns://{APPLIANCE_FQDN}:53",
        filesystem_root="/opt/vis/data/dns",
        settings={
            "protocol": "dns",
            "port": 53,
            "path": "",
            "transport": ["udp", "tcp"],
            "domain": "",
            "default_ttl": 3600,
            "disable_dnssec": False,
            "forward_upstream_enabled": False,
            "forward_upstream_servers": [],
            "entries": [],
        },
        last_validation_result=ValidationResult(False, "DNS Server is not configured yet", ""),
        quick_actions=["Records", "Configure", "Restart"],
    ),
    ServiceDefinition(
        id="time-server",
        name="NTP Server",
        description="Local NTP service for VCF appliances, ESXi hosts, and supporting lab infrastructure.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"ntp://{APPLIANCE_FQDN}",
        filesystem_root="/opt/vis/data/time",
        settings={
            "protocol": "ntp",
            "port": 123,
            "path": "",
            "mode": "ntp",
            "listen_address": "0.0.0.0",
            "allowed_clients": [],
            "upstream_sources": [],
            "local_fallback_enabled": False,
            "fallback_stratum": 10,
            "ptp_enabled": False,
            "ptp_interface": "",
            "ptp_profile": "default",
            "ptp_domain": 0,
            "ptp_transport": "udp4",
            "ptp_timestamping": "auto",
        },
        last_validation_result=ValidationResult(False, "NTP Server is not configured yet", ""),
        quick_actions=["Configure", "Restart"],
    ),
    ServiceDefinition(
        id="dhcp-server",
        name="DHCP Server",
        description="Local DHCP service for lab networks that need appliance-managed address assignment.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"dhcp://{APPLIANCE_FQDN}",
        filesystem_root="/opt/vis/data/dhcp",
        settings={
            "protocol": "dhcp",
            "port": 67,
            "path": "",
            "interface": "",
            "subnet_cidr": "",
            "pool_start": "",
            "pool_end": "",
            "gateway": "",
            "dns_servers": [],
            "domain": "",
            "subnets": [],
            "reservations": [],
            "default_lease_time": 3600,
            "max_lease_time": 7200,
            "authoritative": False,
        },
        last_validation_result=ValidationResult(False, "DHCP Server is not configured yet", ""),
        quick_actions=["Configure", "Restart"],
    ),
    ServiceDefinition(
        id="kms-service",
        name="Key Management Service",
        description="KMIP-compatible key management service for VCF encryption workflows.",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"kmip://{APPLIANCE_FQDN}:5696",
        filesystem_root="/opt/vis/data/kms",
        settings={
            "protocol": "kmip",
            "port": 5696,
            "path": "",
            "provider": "pykmip",
            "listen_address": "0.0.0.0",
            "database_path": "/opt/vis/data/kms/pykmip.db",
            "config_path": "/opt/vis/config/kms/server.conf",
            "tls_enabled": True,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
        },
        last_validation_result=ValidationResult(False, "Key Management Service is not configured yet", ""),
        quick_actions=["Configure"],
    ),
    ServiceDefinition(
        id="content-library",
        name="vSphere Content Library",
        description="vSphere Content Library for Supervisors",
        enabled=False,
        configured=False,
        health_status="needs_configuration",
        endpoint=f"http://{APPLIANCE_FQDN}:9091/",
        filesystem_root="/opt/vis/data/content-library",
        settings={
            "protocol": "http",
            "port": 9091,
            "path": "/",
            "basic_auth_enabled": False,
            "auth_user": "",
            "auth_password": "",
            "source_user": "",
            "source_password": "",
            "source_library_url": "https://wp-content.broadcom.com/v2/latest/lib.json",
            "sync_schedule": "Sun 8:06",
            "tls_enabled": False,
            "tls_mode": "shared",
            "tls_ca_path": "/opt/vis/config/tls/rootCA.pem",
            "tls_cert_path": "/opt/vis/config/tls/server.crt",
            "tls_key_path": "/opt/vis/config/tls/server.key",
            "tls_full_pem_path": "/opt/vis/config/tls/vis-full.pem",
            "auto_source_sync_enabled": True,
            "worker_pool_size": 25,
            "last_sync_time": "",
            "last_sync_duration": 0,
            "last_sync_error": "",
            "total_sync_count": 0,
            "next_sync_time": "",
            "mean_sync_duration": 0,
        },
        last_validation_result=ValidationResult(False, "Content Library is not configured yet", ""),
        quick_actions=["Files", "Configure", "Restart", "Manual Sync"],
    ),
]
